### ISSUE TITLE
fifo_server error

### ISSUE THREAD

**Issue by kaushikb258** [allenai/manipulathor#4]
I am using AI2THOR 2.4. Tried the following but get error

python main.py -o experiment_output -s 1 -b projects/armpointnav_baselines/experiments/ithor/ armpointnav_rgb

05/05 23:15:29 INFO: Running with args Namespace(checkpoint=None, deterministic_agents=False, deterministic_cudnn=False, disable_config_saving=False, disable_tensorboard=False, experiment='armpointnav_rgb', experiment_base='projects/armpointnav_baselines/experiments/ithor/', extra_tag='', gp=None, log_level='info', max_sampler_processes_per_worker=None, mode='train', output_dir='experiment_output', restart_pipeline=False, seed=1, skip_checkpoints=0, test_date=None)	[main.py: 269]
05/05 23:15:29 ERROR: Uncaught exception:	[system.py: 139]
Traceback (most recent call last):
  File "main.py", line 317, in <module>
    main()
  File "main.py", line 273, in main
    cfg, srcs = load_config(args)
  File "main.py", line 233, in load_config
    raise e
  File "main.py", line 230, in load_config
    module = importlib.import_module(module_path)
  File "/home/kb/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kb/CUPS_RL/manipulathor/projects/armpointnav_baselines/experiments/ithor/armpointnav_rgb.py", line 4, in <module>
    from plugins.ithor_arm_plugin.ithor_arm_constants import ENV_ARGS
  File "/home/kb/CUPS_RL/manipulathor/plugins/ithor_arm_plugin/ithor_arm_constants.py", line 3, in <module>
    import ai2thor.fifo_server
ModuleNotFoundError: No module named 'ai2thor.fifo_server'

**Comment by ehsanik** [comment]
Please use the AI2THOR version specified in the repo. 

> AI2-THOR <43f62a0> 🧞. To ensure reproducible results, please install this version of the AI2THOR.

You can download the specified version using the following command:

`pip3 install -e git+https://github.com/allenai/ai2thor.git@43f62a0aa2a1aaafb6fd05d28bea74fdc866eea1#egg=ai2thor`

**Comment by kaushikb258** [comment]
Never mind, I fixed it using a symbolic link:

ln -s src/ai2thor/ai2thor ai2thor

**Comment by kaushikb258** [comment]
Thanks, I now have the AI2THOR version you suggested. Get this error with controller = Controller(....):

Unloading 16 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 10.656555 ms
creating fifo server: /tmp/tmpcftrsg1w/server.pipe 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

client fifo path: /tmp/tmpcftrsg1w/client.pipe 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)


Unloading 3032 unused Assets to reduce memory usage. Loaded Objects now: 36238.
Total: 11.452844 ms (FindLiveObjects: 1.246733 ms CreateObjectMapping: 1.744845 ms MarkObjects: 6.347055 ms  DeleteObjects: 2.111653 ms)

Caught error with invoke for action: Initialize 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Action error message:  
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Traceback (most recent call last):
  File "kb1.py", line 13, in <module>
    fieldOfView=60
  File "/home/kb/ManipulaTHOR/manipulathor/src/ai2thor/ai2thor/controller.py", line 504, in __init__
    event = self.reset(scene)
  File "/home/kb/ManipulaTHOR/manipulathor/src/ai2thor/ai2thor/controller.py", line 630, in reset
    **self.initialization_parameters
  File "/home/kb/ManipulaTHOR/manipulathor/src/ai2thor/ai2thor/controller.py", line 881, in step
    self.last_event.metadata.get("errorMessage", f"{action} failed")
RuntimeError: Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Single'. Path 'massThreshold'. ---> System.InvalidCastException: Null object cannot be converted to a value type.
  at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) [0x00103] in <394015232cf841bc8e43c6c98d8e6545>:0 
   --- End of inner exception stack trace ---
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) [0x00146] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00125] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) [0x00065] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00280] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00161] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00012] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType) [0x002ff] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at Newtonsoft.Json.Linq.JToken.ToObject[T] () [0x00000] in <394015232cf841bc8e43c6c98d8e6545>:0 
  at DynamicServerAction.ToObject[T] () [0x00000] in <8ad1f12e4e1c46019f1c757466d4cd64>:0 
  at ActionDispatcher.Dispatch (System.Object target, DynamicServerAction dynamicServerAction) [0x0004d] in <8ad1f12e4e1c46019f1c757466d4cd64>:0 
  at UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController.ProcessControlCommand (DynamicServerAction controlCommand, System.Object target) [0x00072] in <8ad1f12e4e1c46019f1c757466d4cd64>:0

**Comment by kaushikb258** [comment]
Thanks, I downloaded the version of AI2THOR you suggested. I am able to get the controller act on some of the basic actions (MoveAhead, MoveRight, MoveLeft, RotateLeft, RotateRight, LookUp, LookDown). However, MoveArm and MoveArmBase are throwing an error. Is this an issue with the AI2THOR version? Here is my code:

import ai2thor
from ai2thor.controller import Controller
controller = ai2thor.controller.Controller(agentMode="arm", 
                                           scene="FloorPlan203", 
                                           visibilityDistance=1.5, 
                                           gridSize=0.5, 
                                           renderDepthImage=False, 
                                           renderInstanceSegmentation=False, 
                                           width=224, 
                                           height=224, 
                                           fieldOfView=60)

controller.step(
    action="MoveArm",
    position=dict(x=0, y=0.5, z=0),
    coordinateSpace="armBase",
    restrictMovement=False,
    speed=1,
    returnToStart=True,
    fixedDeltaTime=0.02
)

File "/home/kb/ManipulaTHOR/manipulathor/src/ai2thor/ai2thor/controller.py", line 878, in step
    raise ValueError(self.last_event.metadata["errorMessage"])
ValueError: Invalid action: MoveArm

**Comment by ehsanik** [comment]
There were a couple of API changes in THOR that were resulting in this error. I just updated the code base to work with the newest version of the AI2THOR. Please also read the instructions again. We are now using a pip version of Allenact. Let me know if you face any other problems.

**Comment by kaushikb258** [comment]
Works now. Thanks for the quick response.
